# Generated by Django 5.2 on 2025-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comment_post_comments_reply_comment_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
